project:
  name: quickstart-nasa-jpb-cubs
  owner: quickstart-eng@amazon.com
  package_lambda: false
  s3_regional_buckets: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  quickstart-nasa-jpl-cubs:
    parameters: {}
    template: templates/ammos-cubs.main.template.yaml
