- !EVR
  name: NO_ERROR
  code: 0x0001
  desc: No error
  message: "No error"

- !EVR
  name: EVR_1
  code: 0x0002
  desc: EVR 1
  message: "The first evr"

- !EVR
  name: EVR_2
  code: 0x0003
  desc: EVR 2
  message: "The second evr"

- !EVR
  name: EVR_3
  code: 0x0004
  desc: EVR 3
  message: "The third evr %s"
