// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them
= Additional Info


== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading

TODO: @MF @SL @KM build out
- connect to the AIT Server EC2 Instance and verify services running
- run ait-example and ait-tlm-simulate
- navigate to {FQDN} (app subdomains?) and check GUI availability
- check logs in CW

_Awaiting input from testing lead_

== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading

=== DNS Management
If the user has opted to not use Route53 for domain management and prefers to manage their domain using some other DNS service, they will be responsible for deploying the appropriate name records to their DNS. Refer to your DNS provider’s documentation for guidance on this process. The following records must be deployed (more information can be found in TODO):

    `{fqdn}`           →    `{ALB}`
    `ait.{fqdn}`       →    `{fqdn}`
    `mct.{fqdn}`       →    `{fqdn}`
    `editor.{fqdn}`    →    `{fqdn}`
    `logs.{fqdn}`      →    `{fqdn}`

=== Cognito User Management
Each of the applications is protected by a basic authentication action on the Application Load Balancer. In order for users to access the deployed web applications (AIT, OpenMCT, or Editor), they will need to authenticate using an identity managed by Cognito. It is up to the system administrator to create appropriate user identities in the Cognito User Pool, or set up federation with an existing identity provider.

https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-create-user-accounts.html[Creating User Accounts as Administrator - Amazon Cognito]
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-federation.html[Adding User Pool Sign-in Through a Third Party - Amazon Cognito]

=== AIT Server Management
- Plugin installation [awaiting @KM]
- Config adjustment? [TODO: @MF]
- Server restarts [TODO: @MF]
- Upgrade process? [TODO: @MF]

=== Modifying the CloudWatch Agent
The CloudWatch Agent monitors specified log files and pipes their content to AWS CloudWatch Logs. This file can be found on each server at:
/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

If you wish to monitor additional files, or change the configuration settings, this file can be modified directly according to:
Manually create or edit the CloudWatch agent configuration file - Amazon CloudWatch

Upon editing the file, restart the agent and apply the changes with the following command:
[source,bash]
----
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
    -a fetch-config -s -m ec2 \
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
----

== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

See docs provided in <<Resources,Resources>> below

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

TODO:

@SL:

- Security groups
- Private subnet deployment
- SELinux
- ES/Kibana access policy

@MF:

- Auth actions on ALB
- Code Server user-binding / auth
- SSL terminates at ALB, for ALB, byo
- SSM for instance access


== Resources

=== Docs
AIT:

- https://ait-core.readthedocs.io/en/latest/[AIT-Core 2.3.5 documentation]
- https://ait-gui.readthedocs.io/en/latest/index.html[AIT-GUI 2.3.1 documentation]
- https://ait-dsn.readthedocs.io/en/latest/index.html[AIT-DSN 2.0.0 documentation]

OpenMCT:

- https://nasa.github.io/openmct/[OpenMCT - Open Source Mission Control Software]
- https://nasa.github.io/openmct/docs/guide/index.html#open-mct-developer-guide[Open MCT - Developer Guide]
- https://github.com/nasa/openmct-tutorial[OpenMCT - Integration Tutorials]

=== Community
TODO: @CC Links to other JPL/AMMOS resources

- https://groups.google.com/g/ait-dev[AIT Users Mailing Group]
- https://github.com/nasa/openmct/discussions[OpenMCT - Github Discussions]

== Software version requirements

=== Operating System and dependency versions
All applications are deployed on EC2 instances running Red Hat Enterprise Linux 8 (RHEL8). Although the applications installed via this Quick Start do not have a hard dependency on this specific operating system, it is the officially supported operating system for all AMMOS applications.

The AIT software has only been tested against Python 3.7.x (see the https://ait-core.readthedocs.io/en/latest/installation.html[AIT Docs]), and that is the Python version installed on the application EC2 servers. Python 3.7 is currently not found in any of the official Red Hat Enterprise Linux 8 software repositories, nor is it found in the Red Hat Software Collections. Thus, as part of the deployment, this Quick Start will build/install Python 3.7.9 from source.

=== Application software versions
* AIT: https://github.com/NASA-AMMOS/AIT-Core/releases/tag/2.3.5[2.3.5]
* OpenMCT: https://github.com/nasa/openmct/releases/tag/1.6.2[1.6.2]

The software deployed as part of this Quick Start have the above versions and correspond to the versioned releases in their respective Github repositories. If you require a different version of the software, you can adapt this QuickStart or reinstall the applications at your own risk.

=== InfluxDB

The AIT software installed by this Quick Start is configured with an InfluxDB backend and InfluxDB is installed on the same EC2 server as part of the deployment. The Python library used by AIT to interface with InfluxDB, `influxdb`, is only compatible with InfluxDB versions 1.x and so InfluxDB 1.2.4 is installed during deployment.
