// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them
= Additional Info

== Test the deployment

// TODO: @MF @KM add input if necessary

// If steps are required to test the deployment, add them here. If not, remove the heading
Once the Quick Start has finished deploying, there are some tests you can perform to verify that the various components have been provisioned successfully.

=== Connect to AIT server and AIT Editor instances

. Open the https://console.aws.amazon.com/ec2/[Amazon EC2 console^].
. Choose *Instances* from the left navigation bar.
. On the *Instances* page, confirm that *AitAutoScalingGroup* and *EditorServer* instances display.
. For each instance, ensure that there are no failed checks in the the *Status checks* column.
. Verify that you can connect to each instance using AWS Systems Manager (formerly knows as SSM). 
. Run the following commands to verify that the AIT server `httpd` and `ait-server` services are active:
* `service httpd status`
* `service ait-server status`

. Run `docker ps` to verify that the AIT Editor Docker container is running.

=== Open AIT and Open MCT applications in a web browser
Navigate to the fully qualified domain name (FQDN) entered in the `FQDN` parameter during Quick Start deployment. The deployment uses the `FQDN` parameter in an Amazon Route 53 Canonical Name Record (CNAME record). This record serves as an alias for the Application Load Balancer that directs traffic to AIT server, OpenMCT, and AIT Editor.

Once you have navigated to that URL, you should see an HTML landing page with links to the individual web applications (AIT, OpenMCT, and AIT Editor). Test the links to ensure that you can access each application.

When you visit these applications for the first time, they may prompt you for login credentials. Login credentials are managed by Cognito. For more information, see link:#_cognito_user_management[Cognito User Management], later in this guide.

=== Generate test telemetry
The AIT software includes sample scripts `ait-example` and `ait-tlm-simulate`. They are command line interface (CLI) programs that you run on the AIT server to generate telemetry to test the deployment.

Once you are connected to the AIT server, begin by sourcing and activating the Python virtual environment where AIT and the sample telemetry scripts are installed. The deployment installs the scripts in a virtual environment named `ait` on the AIT server. As part of the activation, the virtual environment modifies your `PATH` variable to include a few AIT scripts that should now be executable.

NOTE: For more information about connecting to the AIT server, see link:#_connect_to_ait_server_and_ait_editor[Connect to AIT server and AIT Editor instances], earlier in this guide.

Use the commands `ait-example` and `ait-tlm-simulate` to run each script, respectively. The two scripts both generate sample telemetry, but `ait-example` has a hard-coded packet structure and will send telemetry for 100 seconds. `ait-tlm-simulate` emits telemetry once per second and can be used to simulate different packet types. `ait-tlm-simulate` is programmed to run indefinitely until the script is stopped.

Navigate to the AIT application (`ait.<fqdn>` in most cases) and choose the *Telemetry* tab. If you are using the default configuration files for AIT provided by the Quick Start deployment, you should see two graphs, one for voltages and one for currents. While the telemetry scripts are running, you should see new data points displaying on the graphs and a line plot forming. This indicates that telemetry is flowing successfully through AIT software.

==== Validate logs in CloudWatch Logs
This deployment includes CloudWatch agents on the AIT and AIT Editor servers configured to send agent and syslog logs to CloudWatch.

To validate that logs are successfully being sent to CloudWatch, open the https://console.aws.amazon.com/cloudwatch/[AWS CloudWatch console]. In the left navigation bar, under *Logs*, choose *Log groups*. On the *Log groups* page, locate the following log groups:

* `/cloudwatch-agent/ait-editor/agent`
* `/cloudwatch-agent/ait-editor/syslog`
* `/cloudwatch-agent/ait-server/agent`
* `/cloudwatch-agent/ait-server/syslog`

Verify that there are log data in log streams for each log group. 

NOTE: Do not expect a lot of log data in streams if you check shortly after the Quick Start is deployed.

//TODO: is this input complete? is more needed?
//_Awaiting input from testing lead_

== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading

=== DNS management
If you have opted to not use Route 53 for domain management, you are responsible for deploying the appropriate name records to your DNS. Refer to your DNS provider’s documentation for guidance on this process. The following records must be deployed:

    CNAME         fqdn            →    ALB
    Alias    |    ait.fqdn        →    fqdn
    Alias    |    mct.fqdn        →    fqdn
    Alias    |    editor.fqdn     →    fqdn
    Alias    |    logs.fqdn       →    fqdn

//TODO LINK: Link to ALB Stack or properly name once available  -- Is this done?

[NOTE]
====
* To view the Application Load Balancer DNS name, see the value displayed in the *Outputs* tab for the stack.
* The Application Load Balancer will handle redirection based on host header in request, thus it is sufficient to deploy a single CNAME record pointing at the Application Load Balancer, and all subdomains as aliases redirecting to the Application Load Balancer CNAME.
====

=== Cognito user management
The Application Load Balancer defines an authentication action to protect the AIT, Open MCT, and AIT Editor applications. To access the applications, a user must authenticate using an identity managed by Cognito. You must create user identities in the Cognito user pool or set up federation with an existing identity provider. For more information, see https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-create-user-accounts.html[Creating User Accounts as Administrator] and https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-federation.html[Adding User Pool Sign-in Through a Third Party].

=== AIT server management
The AIT Server will likely require further adaptation by the mission both at launch, and as the needs and parameters of the mission evolves over its lifetime. These changes can be made directly on the server over an SSH or SSM-Managed session; some common adaptations are described below.

==== Virtual environment (virtualenvwrapper)
The AIT Server installs AIT-Core, several plugins, and various dependencies to a python virtual environment. This is facilitated by the virtualenvwrapper python tool as suggested by the AIT Core documentation; see: +
https://ait-core.readthedocs.io/en/master/installation.html#installation[Installation and Environment Configuration — AIT-Core 2.3.5 documentation.]

The creation and configuration of this environment follows the guidance of AIT Core documentation. The environment can be activated via the command:

[source,bash]
workon ait

==== Plugin installation
//TODO: awaiting @KM
// ^ Request is pending, for now the following is sufficient
AIT is a highly extensible framework designed to allow mission teams to adapt it to their specific needs. AIT provides several extensions such as the Data Archive, DSN, and Open MCT plugins, and also allows users to develop and include their own plugins. More information can be found in the AIT documentation:

- https://ait-core.readthedocs.io/en/master/server_architecture.html#plugins[AIT Docs - Plugins]
- https://ait-core.readthedocs.io/en/master/extensions.html[AIT Docs - Extensions]
- https://ait-core.readthedocs.io/en/master/server_architecture.html#plugins[AIT Docs - Plugins]

==== Config Management
Upon launch, a set of config files are brought down to the server from S3 and placed in `/home/ec2-user/AIT-Core/config` (more info on this S3 bucket can be found here LINK: link to `pre-reqs.Configuration files in S3`). Any of these config files can be modified directly on the server, or replaced by new files uploaded to S3. For any config changes to take effect, the `ait-server` systemd service will need to be restarted as described in LINK: link to `additional_info.Systemd Services`.

New files can be brought down from S3 via

    aws s3 sync s3://<BUCKET_NAME>/ait/config /home/ec2-user/AIT-Core/config

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html[AWS CLI - S3 Sync]

==== Server Restarts
The AIT Server and other critical services (InfluxDB and HTTPD) are enabled as `systemd` services. These are all described in more depth in below.

The EC2 Instance can be stopped and restarted as needed; all system services will be brought online upon restart.

==== Upgrades
If the user desires to upgrade AIT-Core or any of the other included applications, they can do so at their own risk; however, this Quick Start only supports those versions listed below LINK: link to `Software version requirements`.

To upgrade any of the applications, the user should refer to that applications user guide. Be sure to backup any the config directory and any other modified files. The cloned application repositories can then be updated and reinstalled to the virtual environment as noted below.

==== Open MCT Static Built Files
The Open MCT framework is written in JavaScript and can be compiled, minified, and bundled into a set of static assets that can be served from a web server. In this Quick Start, the latest version of Open MCT has been packaged and uploaded to S3 as a zip file.

Upon deployment of the Quick Start, the zip file is downloaded from S3 and extracted so that it can be served by Apache HTTP Server.

On the server, the static files are extracted and located at `var/www/html/openmct`.

Any configuration changes and additional plugins for OpenMCT will have to be placed in this directory. Visit the dogs for more information on https://github.com/nasa/openmct/blob/master/API.md#building-applications-with-open-mct[Building Applications with OpenMCT].

==== Systemd services - AIT server
The following services are managed by `systemd` on the application server:

===== HTTPD
Apache HTTP Server is installed and managed as a `systemd` service. The service file can be found at: +
`/usr/lib/systemd/system/httpd.service`

The service should be running by default upon successfully provisioning the instance. The status can be checked via:

[source,bash]
sudo systemctl status httpd

The Apache HTTP Server routes incoming traffic to both AIT or OpenMCT.

Apache configuration files are located at `/etc/httpd`. The base configuration can be found at `/etc/httpd/conf/httpd.conf`, and supplemental configuration files can be found at `/etc/httpd/conf.d`.

===== InfluxDB
InfluxDB iis installed and managed as a `systemd` service. The service file can be found at: +
`/usr/lib/systemd/system/influxdb.service`

The service should be running by default upon successfully provisioning the instance. The status can be checked via:
sudo systemctl status influxdb

This Quick Start uses an out-of-the-box setup for InfluxDB with very few changes. InfluxDB is used as a data storage layer for the AIT application.

===== AIT server
The AIT-Core server is installed and managed as a `systemd` service. The service file can be found at: +
`/etc/systemd/system/ait-server.service`

The service should be running by default upon successfully provisioning the instance. The status can be checked via:

[source,bash]
sudo systemctl status ait-server

If changes are made to the AIT config files, the service will need to be restarted before changes are applied. This can be done via:

[source,bash]
sudo systemctl restart ait-server

The service itself will run the AIT Core Server which listens for, processes, and exposes telemetry. Additionally, any configured plugins (such as `AIT-GUI`) will also be run according to the main AIT config file.

== Logging (CloudWatch agent)

To facilitate centralized logging for the various applications, the Amazon CloudWatch Agent is installed on all of the deployed EC2 Instances during the bootstrap process. This agent is initialized by a provided default config file which informs the agent which files to monitor and where to direct the logs in AWS CloudWatch.

//TODO: please confirm these links? are they links to section in this guide?
The default configuration files can be inspected at LINK: link to S3 config. Users may modify this file in the post-deployment steps as detailed in LINK: link to post-deploy.

For more information about the CloudWatch Agent, see:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html[Collecting metrics and logs from Amazon EC2 instances and on-premises servers with the CloudWatch agent - Amazon CloudWatch]

=== Log retention settings

The AWS CloudWatch log groups that receive logs from the various applications have been configured with a log retention period. The retention period is a parameter in the logging CloudFormation template and can be adjusted by changing the parameter value prior to deployment or by https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#SettingLogRetention[manually changing the retention period]. The default log retention period is 30 days (a month). Keep in mind that increasing the log retention period will increase the costs associated with storing the logs for a longer time.

=== Modifying the CloudWatch agent
The CloudWatch Agent monitors specified log files and pipes their content to AWS CloudWatch Logs. This file can be found on each server at:
/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

If you wish to monitor additional files, or change the configuration settings, this file can be modified directly according to:
Manually create or edit the CloudWatch agent configuration file - Amazon CloudWatch

Upon editing the file, restart the agent and apply the changes with the following command:
[source,bash]
----
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
    -a fetch-config -s -m ec2 \
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
----

== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

See docs provided in <<Resources,Resources>> below

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

=== IAM

In order to facilitate compliance with organizational restrictions on IAM Role creation, the following parameters are available on all stacks which create IAM Roles:

* PermissionsBoundaryArn: ARN of a Managed Policy in your account to be used as the permissions boundary for the created role. +
    See https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html[Permissions boundaries for IAM entities - AWS Identity and Access Management] for more info.
* RolePath: String used as the path attribute for the created role. +
    See https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-friendly-names[IAM identifiers - AWS Identity and Access Management] for more info.

These attributes will not be set if the parameter is not supplied.

=== Security groups
As part of the Quick Start deployment, you must specify security groups that define inbound and outbound network traffic rules. This involves creating inbound rules for the security groups and defining the appropriate CIDR/IP ranges that are allowed inbound access to various resources deployed by this Quick Start. For more information, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html[Amazon EC2 security groups for Linux instances].

=== Private subnets
The application servers for AIT Server and AIT Editor as well as the Elasticsearch domain are deployed to private subnets within a VPC. An Application Load Balancer (deployed to a public subnet in the same VPC) is used to route requests to these servers. This minimizes the publicly exposed footprint of resources deployed using this Quick Start. To access these servers in the private subnets, please refer to <<SSM,documentation section on SSM (Systems Manager)>>.

=== SELinux
SELinux is enabled and enforced on the application servers. Apache HTTP Server and the various application processes have been configured for SELinux compatibility and can be run without disabling SELinux.

Side effects may occur if settings and/or configuration files are modified or moved after the initial deployment of the application. If you have any issues with SELinux file and process contexts, please refer to a fresh deployment of the Quick Start or redeploy the Quick Start.

IMPORTANT: We highly recommend you do not disable SELinux unless you are aware of unintended security consequences or have the need to disable SELinux for compatibility or debugging purposes.

=== Elasticsearch/Kibana
This Quick Start deploys an Elasticsearch domain under the AWS Elasticsearch Service. The Elasticsearch domain contains logging data that is received from application servers. It is deployed within a VPC (see https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html[VPC support]) and all master and data nodes reside within private subnets. Encryption for data at rest is enabled by default, and the security group associated with the domain is configured prior to deploying this Quick Start.

IMPORTANT: The Elasticsearch domain currently uses an open access policy, with access controlled via by an EC2 security group. For more security, use fine-grained access control or modify the access policy to specify IAM users or roles. See https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/security.html[Elasticsearch security] for more details.

//TODO: what needs to be added/clarified here?
//@MF:

=== Authentication
The Application Load Balancer is deployed to a public subnet and brokers access to the application resources deployed in private subnets. Each application is accessible via a Listener Rule which directs traffic according to the host header and performs an authentication action prior to forwarding the traffic to the appropriate target group. 

This authentication action is configured with the deployed AWS Cognito user pool as an OpenID Connect (OIDC) provider. Access is granted on a full-access basis, if a user can authenticate as a known identity, they are allowed through the Application Load Balancer to the underlying resource.

For more information on Application Load Balancer authentication actions, see the following resources:

- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html[Authenticate users using an Application Load Balancer]
- https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/[Simplify Login with Application Load Balancer Built-in Authentication]

=== Code-server access
// TODO: mitigate impact from what? 
The AIT Editor server runs `cdr/code-server`. Visual Studio Code includes an integrated terminal that allows you to execute system-level commands from a browser. To mitigate impact, the Visual Studio Code server runs in a Docker container with volumes mounted to the following locations:

- /home/editor-user/.aerie-editor-data:/home/coder/.local/share/code-server
- /home/editor-user/.aerie-editor-config:/home/coder/.config
- /home/editor-user:/home/coder/project

For information on changing the password in the code-server configuration file, see https://coder.com/docs/code-server/v3.11.1/FAQ#how-do-i-change-the-password[How do I change the password?]

=== SSL
The Application Load Balancer uses HTTPS listeners. Clients that access applications through the Application Load Balancer will have their traffic encrypted using SSL/TLS. Any normal HTTP traffic going to the Application Load Balancer is redirected to the HTTPS listener.

An X.509 certificate must be provided during Quick Start deployment in order to configure the Application Load Balancer for SSL/TLS.

SSL termination occurs at the Application Load Balancer. Communication to the server targets behind the Application Load Balancer is unencrypted, albeit through private VPC subnets.

=== AWS Systems Manager
Users should connect to the application servers via AWS Systems Manager for improved security and monitoring. The deployment installs AWS Systems Manager Agent (SSM Agent) on all instances. Additionally, each instance profile is assigned the AWS managed service role `AmazonSSMManagedInstanceCore`.

Users can provide the `SshKeyName` parameter to the relevant templates to enable standard SSH connections. The Quick Start deploys instances in a private subnet which are not discoverable directly from the internet. To connect via SSH, you must provision a bastion host (jump server). For more information on starting a session with Systems Manager, see https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-sessions-start.html[Start a session].

== Resources

=== Docs
AIT

- https://ait-core.readthedocs.io/en/latest/[Welcome to the AMMOS Instrument Toolkit (AIT) documentation!]
- https://ait-gui.readthedocs.io/en/latest/index.html[Welcome to the AMMOS Instrument Toolkit GUI documentation!]
- https://ait-dsn.readthedocs.io/en/latest/index.html[Welcome to AIT DSN’s documentation!]

OpenMCT

- https://nasa.github.io/openmct/[Open MCT]
- https://nasa.github.io/openmct/docs/guide/index.html#open-mct-developer-guide[Open MCT - Developer Guide]
- https://github.com/nasa/openmct-tutorial[Open MCT Integration Tutorials]

// AIT Editor:

//TODO: @MF links to AIT Editor once available
// ^ Request is pending final open source approval

=== Community

- https://groups.google.com/g/ait-dev[AIT Users Mailing Group]
- https://github.com/nasa/openmct/discussions[OpenMCT - Github Discussions]

== Software version requirements

=== Operating system and dependency versions
The Quick Start deploys AIT, Open MCT, and AIT Editor on EC2 instances running Red Hat Enterprise Linux 8 (RHEL8). These applications do not require RHEL8, but RHEL8 is the officially supported operating system for all AMMOS applications.

The Quick Start builds and installs Python 3.7.x on the application EC2 instances. This is the version that AIT software supports. Python 3.7 is not part of the official Red Hat Enterprise Linux 8 software repositories or Red Hat Software collections. For more information, see https://ait-core.readthedocs.io/en/latest/installation.html[Installation and Environment Configuration].

=== Application software versions
This Quick Start deploys and supports https://github.com/NASA-AMMOS/AIT-Core/releases/tag/2.3.5[AIT version 2.3.5] and https://github.com/nasa/openmct/releases/tag/1.6.2[Open MCT version 1.6.2].

=== InfluxDB

This Quick Start deploys InfluxDB version 1.2.4 on the AIT server EC2 instances. The influxdb Python library used by AIT to interface with InfluxDB is only compatible with InfluxDB versions 1.x.
