// If no preparation is required, remove all content from here

== Prepare your AWS account

_Describe any setup required in the AWS account prior to template launch_

TODO:
=== Deploy vpc and config stacks (pre-deploy) //TODO: @AG


== Deploy SLR for ES
A service-linked role must be created in your AWS account before an Elasticsearch domain can be created as a part of Quick Start deployment.

The serviced to use the service-linked role is `es.amazonaws.com`.  The serviced-linked role will allow Elasticsearch to call other necessary AWS services on your behalf during the Elasticsearch provisioning process.

For more information on how to create a service-linked role for Elasticsearch, see the https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html[AWS Elasticsearch documentation], or the https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html#create-service-linked-role[documentation for creating service-linked roles].

== Add ingress rules to “access-sg"
As part of the VPC deployed above, a Security Group is created to manage allowed ingress to protected applications. This security group will be attached to various resources during the QS deployment, allowing access based on the SG Ingress Rules. At a minimum, ingress rules should be added for user-controlled IP blocks on following ports:

- 22: Allow SSH to bastion resource
- 443: Allow HTTPS traffic to the ALB which exposes application resources on the web (AIT-GUI, OpenMCT, Editor)
- 80: Allow HTTP discovery of ALB (will redirect to HTTPS)
- 8082: Allow retrieval of live telemetry from AIT-MCT plugin

[NOTE]
====
If Security Group is opened to the world, resources will still be protected by ALB Authentication Actions and AWS SSM; for more info, see TODO: link to security
====

For more information on adding Security Group Ingress Rules, see: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html[AWS Docs - Security Groups Basics]

== Check config bucket contents and replace with mission-specific config
During Quick Start deployment, an S3 Bucket is created and populated with base configuration files for AIT Server, AIT Editor, and OpenMCT.

If you would like to use your own configuration files, copy and overwrite files of the same name in the S3 configuration files bucket. For a layout of the configuration S3 Bucket and an overview of available configuration files, see <<Configuration files in S3, Configuration files in S3>>.

IMPORTANT: To ensure successful deployment of the applications, make sure your configuration files have the correct syntax and format. For more more information about AIT configuration, see the https://ait-core.readthedocs.io/en/latest/configuration_intro.html[AIT Documentation]

== Import user-owned domain to Route53 (optional)
The deployment relies on a user-provided domain (referred to as `fqdn`); This FQDN is used to discover the ALB and subdomains identify each application. The following records will be deployed in the user-provided Route53 Hosted Zone for each application:

    fqdn            →    ALB
    ait.fqdn        →    AIT ASG [apache → ait-gui bottle app]
    mct.fqdn        →    AIT ASG [apache → mct static built app]
    editor.fqdn     →    Editor EC2 Instance [docker container]
    logs.fqdn       →    ElasticSearch/Kibana

For guidance on creating a Route 53 Hosted Zone, see: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring.html[AWS Docs - Configuring Route53 as your DNS Service]

If the user chooses not to use Route53, they are responsible for deploying the appropriate records as detailed in TODO: link to post-deployment step

== Import ssl certificate to AWS ACM
HTTPS is enabled on the ALB, requiring a valid SSL certificate for the aforementioned `FQDN`; additionally, the certificate should include the following alternative SANs (`*.{FQDN}` may be used if desired):

- `ait.{FQDN}`
- `mct.{FQDN}`
- `editor.{FQDN}`
- `logs.{FQDN}`

This certificate will need to be available in AWS Certificate Manager (ACM) for attachment to the ALB. For detailed instructions on requesting or importing a certificate with ACM

- https://docs.aws.amazon.com/acm/latest/userguide/gs.html[AWS User Guide - ACM: Issue and Manage Certificates]
- https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[AWS User Guide - ACM: Import Certificates]


== Prepare your {partner-company-name} account

_Describe any setup required in the partner portal/account prior to template launch_

None required - all products are FOSS (we think)

== Prepare for the deployment

_Describe any preparation required to complete the product build, such as obtaining licenses or placing files in S3_

=== Configuration files in S3
For configuration and settings, an S3 bucket is created as part of the deployment and seeded with a set of default configuration files. Within the bucket, the configuration files have been organized by application with the following file structure:

----
s3
├── ait
│   ├── cloudwatch-agent-ait.json
│   ├── config
│   │   ├── bsc.yaml
│   │   ├── ccsds_header.yaml
│   │   ├── cmd.pkl
│   │   ├── cmd.yaml
│   │   ├── config.yaml
│   │   ├── core_set_op_mode.yaml
│   │   ├── evr.pkl
│   │   ├── evr.yaml
│   │   ├── leapseconds.dat
│   │   ├── limits.pkl
│   │   ├── limits.yaml
│   │   ├── table.yaml
│   │   ├── tlm.pkl
│   │   └── tlm.yaml
│   └── httpd_proxy.conf
├── editor
│   └── cloudwatch-agent-editor.json
└── modules
    └── openmct-static.tgz
----

==== ait/
Files in this S3 path are configuration files for the AIT deployment within this Quick Start.

===== cloudwatch-agent-ait.json
This file is used to configure the CloudWatch agent that will run on the AIT EC2 server instance. If you would like to add additional sources for logs that will be sent to CloudWatch Logs, edit this config to enable those new log sources.

For more information about modifying the CloudWatch agent configuration file, see the https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html[AWS CloudWatch agent documentation].

===== config/
All files in this S3 path are configuration files for the AIT application. These files can be modified and overwritten in S3 to customize the AIT server installation. The main configuration file is `config.yaml`, however any of the other files may be modified or overwritten depending on your needs.

===== config.yaml
This file is the main configuration file for AIT. On the AIT EC2 service instance, this file is located at `/home/ec2-user/AIT-Core/config/config.yaml`.

This main configuration file references a few other configuration files (filepaths are relative) as well as enabling a default set of AIT plugins - AIT GUI, the Data Archive plugin for InfluxDB, and the AIT Open MCT Plugin.

For more information on this file, see the https://ait-core.readthedocs.io/en/latest/configuration_intro.html#config-yaml[AIT documentation].

===== httpd_proxy.conf
This configuration file defines how Apache HTTP Server proxies requests to either AIT or OpenMCT. Both applications are set up as virtual hosts in Apache. Requests to AIT get proxied to the AIT backend Python process while requests to OpenMCT are handled directly by the Apache web server which is serving OpenMCT’s static files.

This file typically does not need to be modified unless you want a non-standard configuration for routing traffic between applications. For more detailed information on how to modify this file, please see the https://httpd.apache.org/docs[Apache HTTP Server Project documentation].


==== editor/
Files in this S3 path are configuration files for the AIT Editor deployment within this Quick Start.

===== cloudwatch-agent-editor.json
This file is used to configure the CloudWatch agent that runs on the AIT Editor EC2 server instance. If you would like to configure additional sources for logs that will be sent to CloudWatch Logs, edit this config to enable those sources.

For more information about modifying the CloudWatch agent configuration file, see the https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html[AWS CloudWatch agent documentation].

==== modules/
Files in this S3 path are static files that are served via Apache HTTP Server.

===== openmct-static.tgz
This file is a tarball of the static files for OpenMCT. The JavaScript files in the tarball have been minified and bundled.

If you would like to modify the OpenMCT framework or configure/install plugins for OpenMCT, you may make your changes, create a new tarball, and then upload new file to overwrite the existing file in S3.
