// If no preparation is required, remove all content from here

== Prepare your AWS account

// _Describe any setup required in the AWS account prior to template launch_
Before you launch the Quick Start, complete the following steps.

=== 1. Create a service-linked role for Amazon ES
A service-linked role allows Amazon ES to call other necessary AWS services on your behalf during the Amazon ES provisioning process. To create the role, follow the instructions under https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html#create-service-linked-role[Creating a service-linked role^]. Specify the service name as `es.amazonaws.com`.

For more information, see the https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html[Using service-linked roles to provide Amazon Elasticsearch Service access to resources^].

=== 2. Deploy the preconfiguration stack
You must deploy the preconfiguration (prerequisite) stack so that you can customize the configuration files, as detailed in the following step.  

http://qs_launch_permalink[Deploy the preconfiguration stack^].

//TODO Andrew, What full URL should this permalink map to?

===  3. Customize the configuration files

The preconfiguration stack that you deployed in the previous step contains an S3 bucket that's populated with base configuration files for AIT Server, AIT Editor, and Open MCT. Customize these files as follows:

. Sign in to the AWS Management Console, and open the AWS CloudFormation console.
. Select the newly deployed preconfiguration stack, choose the *Outputs* tab, and note the configuration bucket name (the value of the *ConfigBucket* key).
. Copy, customize, and overwrite files of the same name in the S3 configuration bucket. For details on how to customize the configuration files, see the following section. For more information, see https://ait-core.readthedocs.io/en/latest/configuration_intro.html[Introduction to AIT Configuration^].
+
IMPORTANT: Use the correct syntax and format in your configuration files so that the applications deploy.

==== How to customize the configuration files
The configuration files in the S3 bucket are organized by application with the following structure:

----
configs
├── ait
│   ├── cloudwatch-agent-ait.json
│   ├── config
│   │   ├── bsc.yaml
│   │   ├── ccsds_header.yaml
│   │   ├── cmd.pkl
│   │   ├── cmd.yaml
│   │   ├── config.yaml
│   │   ├── core_set_op_mode.yaml
│   │   ├── evr.pkl
│   │   ├── evr.yaml
│   │   ├── leapseconds.dat
│   │   ├── limits.pkl
│   │   ├── limits.yaml
│   │   ├── table.yaml
│   │   ├── tlm.pkl
│   │   └── tlm.yaml
│   └── httpd_proxy.conf
├── editor
│   └── cloudwatch-agent-editor.json
└── modules
    └── openmct-static.tgz
----

===== configs/ait/
Files in this S3 path are configuration files for the AIT deployment within this Quick Start.

===== cloudwatch-agent-ait.json
This file is used to configure the CloudWatch agent that runs on the AIT EC2 server instance. If you would like to add sources for logs that will be sent to CloudWatch Logs, edit this file to enable those new log sources.

For more information about modifying the CloudWatch agent configuration file, see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html[Manually create or edit the CloudWatch agent configuration file^].

===== config/
All files in this S3 path are configuration files for the AIT application. The main configuration file is `config.yaml`. You can modify and overwrite any of the other files to customize the AIT server installation. 
//TODO: "The main configuration file is `config.yaml`" this implies that this file should not be overwritten? Clarify here and in the following section. (People may not read both.)

===== config.yaml
This file is the main configuration file for AIT. On the AIT EC2 service instance, this file is located at `/home/ec2-user/AIT-Core/config/config.yaml`.

This main configuration file references a few other configuration files (filepaths are relative) as well as enabling a default set of AIT plugins: AIT GUI, the Data Archive plugin for InfluxDB, and the AIT Open MCT plugin.

For more information, see https://ait-core.readthedocs.io/en/latest/configuration_intro.html#config-yaml[config.yaml^] in the AIT documentation.

===== httpd_proxy.conf
This configuration file defines how Apache HTTP Server proxies requests to either AIT or Open MCT. Both applications are set up as virtual hosts in Apache. Requests to AIT get proxied to the AIT backend Python process while requests to Open MCT are handled directly by the Apache web server that serves Open MCT’s static files.

You don't typically modify this file, but you can if you want a nonstandard configuration for routing traffic between applications. For more information on how to modify this file, see https://httpd.apache.org/docs[Apache HTTP Server Documentation^].

===== configs/editor/
Files in this S3 path are configuration files for the AIT Editor deployment within this Quick Start.

===== cloudwatch-agent-editor.json
This file configures the CloudWatch agent that runs on the AIT Editor EC2 server instance. If you want to configure additional sources for logs that will be sent to CloudWatch Logs, edit this file.

For more information about modifying the CloudWatch agent configuration file, see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html[Manually create or edit the CloudWatch agent configuration file^].

===== configs/modules/
Files in this S3 path are static files that are served by Apache HTTP Server.

===== openmct-static.tgz
This file is a tarball of the static files for Open MCT. The JavaScript files in the tarball have been minified and bundled.

If you want to modify the Open MCT framework or configure or install plugins for Open MCT, make your changes, create a new tarball, and then upload the new file to overwrite the existing file in S3.

=== 4. (Optional) Import a user-owned domain into Route 53
The deployment relies on a user-provided fully qualified domain name (FQDN). This FQDN is used to discover the Application Load Balancer and subdomains to identify each application. The following records will be deployed in the user-provided Route53 Hosted Zone for each application:

    fqdn            →    ALB
    ait.fqdn        →    AIT ASG [apache → ait-gui bottle app]
    mct.fqdn        →    AIT ASG [apache → mct static built app]
    editor.fqdn     →    Editor EC2 instance [docker container]
    logs.fqdn       →    Amazon ES/Kibana

For guidance on creating a Route 53 Hosted Zone, see: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring.html[AWS Docs - Configuring Route53 as your DNS Service]

If you choose not to use Route53, you are responsible for deploying the appropriate records as detailed in <<_dns_management>>. Additionally, you will need to import an SSL certificate into AWS Certificate Manager (ACM), as outlined below.

=== 5. Import SSL certificate to ACM

This deployment applies an SSL certificate to the Application Load Balancer. This certificate can be imported manually into ACM, or generated as part of the deployment.

HTTPS is enabled on the Application Load Balancer, requiring a valid SSL certificate for the FQDN. Additionally, the certificate should include the following alternative SANs (`*.{FQDN}` may be used):

- `ait.{FQDN}`
- `mct.{FQDN}`
- `editor.{FQDN}`
- `logs.{FQDN}`

This certificate needs to be available in ACM for attachment to the Application Load Balancer. For details on requesting or importing a certificate with ACM, see the following:

- https://docs.aws.amazon.com/acm/latest/userguide/gs.html[AWS User Guide - ACM: Issue and Manage Certificates]
- https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[AWS User Guide - ACM: Import Certificates]

If the `DomainName` and `HostedZoneID` parameters are populated, this deployment generates an ACM certificate. This deployment method uses DNS validation. All underlying DNS records relating to the ACM certificate will be created as necessary.