// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding.
// Include the benefits of using the software on AWS, and provide details on usage scenarios.

The {partner-product-short-name} Quick Start deploys a collection of software that you use, mostly through web-based interactions, to plan and operate small satellites (SmallSats and CubeSats). You can also use this software to control other complex instruments used in space missions, such as ____.

//TODO Andrew, Please fill in the blank.

This software has three main components:

* AMMOS Instrument Toolkit (AIT)
* Open Mission Control Technologies (Open MCT) Toolkit
* AIT Editor

=== AIT
// Following pulled from AIT-Core readthedocs
// https://ait-core.readthedocs.io/en/latest/index.html#welcome-to-the-ammos-instrument-toolkit-ait-documentation
At the core of this Quick Start, AIT is a Python-based software suite that handles a ground data system (GDS) and electronic ground-support equipment (EGSE). It also handles commanding, telemetry uplink and downlink, sequencing for the JPL International Space Station (ISS), and CubeSat missions. It's an expansion of tools that were developed for JPL ISS missions.

=== Open MCT Toolkit
// Following pulled from Open MCT's README on GitHub
// https://github.com/nasa/openmct/blob/master/README.md
The Open MCT Toolkit provides data-visualization and dashboard capabilities on desktop and mobile devices. NASA uses this toolkit, which was developed at their Ames Research Center, to analyze data from spacecraft missions and to plan and operate experimental rover systems. As a generalizable and open-source framework, you could use Open MCT as the basis for building applications for planning, operating, and analyzing any system that produces telemetry data.

=== AIT Editor
//TODO: @MF Replace or augment with official content from AIT Editor team once available
// ^ request is out for AIT Editor team, what's here is fine for now
You use AIT Editor to generate and edit spacecraft command-sequence files. An extension for Microsoft Visual Studio Code (VS Code or VSC), AIT Editor is published on the VSC Marketplace. This tool reads in the same configuration files used by AIT to perform syntax checking and validation of command-sequence files. While this extension can be installed locally on any VSC client, this Quick Start deployment includes a centralized browser-based integrated development environment (IDE) based on https://github.com/cdr/code-server[code-server^]. With this open-source application, you can run VS Code on any machine. The central AIT Editor server that's deployed in this Quick Start installs and configures code-server, the AIT Editor extension, and the mission configuration used by AIT.

NOTE: Since code-server can't use Microsoft's extension marketplace due to Microsoft's terms of service for VSC, you install the AIT Editor extension manually from the VSIX file published on GitHub and the Marketplace. For details, see the https://coder.com/docs/code-server/v3.11.1/FAQ#why-cant-code-server-use-microsofts-extension-marketplace[code-server FAQ^].


//LINK: link to resources section in additional_info
