= Miscellaneous

Some random tid-bits that are important to know - not sure where to put them yet, just want to get them noted first.

== DNS
The deployment relies on a user-provided domain `fqdn` (e.g. apollo.snasa.gov)
The following records will be deployed as subdomains for each application

    fqdn        →    ALB
    ait.fqdn    →    AIT ASG [apache → ait-gui bottle app]
    mct.fqdn    →    AIT ASG [apache → mct static built app]
    editor.fqdn    →    Editor EC2 Instance [docker container]
    logging.fqdn    →    ElasticSearch/Kibana

If the user chooses not to use Route53, they are responsible for deploying the following records:

    CNAME    fqdn        →    ALB
    Alias    |    ait.fqdn    →    fqdn
    Alias    |    mct.fqdn    →    fqdn
    Alias    |    editor.fqdn    →    fqdn
    Alias    |    logging.fqdn    →    fqdn

The ALB will handle the appropriate redirection based on host header in request, thus it is sufficient to deploy a single CNAME record pointing at the ALB, and all subdomains as aliases redirecting to the ALB CNAME

== Log Retention Settings

The AWS CloudWatch log groups that receive logs from the various applications have been configured with a log retention period. The retention period is a parameter in the logging CloudFormation template and can be adjusted by changing the parameter value prior to deployment or by https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#SettingLogRetention[manually changing the retention period]. The default log retention period is 30 days (a month). Keep in mind that increasing the log retention period will increase the costs associated with storing the logs for a longer time.

== IAM PermissionsBoundary and RolePath

In order to facilitate compliance with organizational restrictions on IAM Role creation, the following parameters are available on all stacks which create IAM Roles:

* PermissionsBoundaryArn: ARN of a Managed Policy in your account to be used as the permissions boundary for the created role. +
    See https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html[Permissions boundaries for IAM entities - AWS Identity and Access Management] for more info.
* RolePath: String used as the path attribute for the created role. +
    See https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-friendly-names[IAM identifiers - AWS Identity and Access Management] for more info.

These attributes will not be set if the parameter is not supplied.

== AIT Server Resiliency
...tbd...

== Logging (CW Agent)

To facilitate centralized logging for the various applications, the Amazon CloudWatch Agent is installed on all of the deployed EC2 Instances during the bootstrap process. This agent is initialized by a provided default config file which informs the agent which files to monitor and where to direct the logs in AWS CloudWatch.

The default configuration files can be inspected at TODO. Users may modify this file in the post-deployment steps as detailed in TODO.

For more information about the CloudWatch Agent, see:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html[Collecting metrics and logs from Amazon EC2 instances and on-premises servers with the CloudWatch agent - Amazon CloudWatch]

== SSM Agent
Users are directed to connect to the application servers via AWS SSM for improved security and monitoring. To facilitate this, the AWS SSM Agent is installed on all instances during bootstrapping. Additionally, each Instance Profile is assigned the AWS-managed service role   `AmazonSSMManagedInstanceCore`.

Additionally, users can provide the SshKeyName parameter to the relevant templates to enable standard ssh connections. However, because the instances are provisioned in a private subnet, they will not be directly discoverable from the internet. To connect via SSH, a vpc-deployed bastion or “jump server” will need to be provisioned. Alternatively, see the below documentation for guidance on starting an SSH session via AWS SSM

Sessions can be started via the AWS-provided web interface, or from a terminal. Both methods are documented here: +
https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-sessions-start.html[Start a session - AWS Systems Manager]

== Virtual Environment (virtualenvwrapper)
The AIT Server installs AIT-Core, several plugins, and various dependencies to a python virtual environment. This is facilitated by the virtualenvwrapper python tool as suggested by the AIT Core documentation; see: +
https://ait-core.readthedocs.io/en/master/installation.html#installation[Installation and Environment Configuration — AIT-Core 2.3.5 documentation.]

The creation and configuration of this environment follows the guidance of AIT Core documentation. The environment can be activated via the command:

[source,bash]
workon ait

== OpenMCT Static Built Files
The OpenMCT framework is written in JavaScript and can be compiled, minified, and bundled into a set of static assets that can be served from a web server. In this Quick Start, the latest version of OpenMCT has been packaged and uploaded to S3 as a zip file.

Upon deployment of the Quick Start, the zip file is downloaded from S3 and extracted so that it can be served by Apache HTTP Server.

On the server, the static files are extracted and located at `var/www/html/openmct`.

Any configuration changes and additional plugins for OpenMCT will have to be placed in this directory. Visit the dogs for more information on https://github.com/nasa/openmct/blob/master/API.md#building-applications-with-open-mct[Building Applications with OpenMCT].

== Services
The following services are managed by `systemd` on the application server:

=== HTTPD
Apache HTTP Server is installed and managed as a `systemd` service. The service file can be found at: +
`/usr/lib/systemd/system/httpd.service`

The service should be running by default upon successfully provisioning the instance. The status can be checked via:

[source,bash]
sudo systemctl status httpd

The Apache HTTP Server routes incoming traffic to both AIT or OpenMCT.

Apache configuration files are located at `/etc/httpd`. The base configuration can be found at `/etc/httpd/conf/httpd.conf`, and supplemental configuration files can be found at `/etc/httpd/conf.d`.

== InfluxDB
InfluxDB iis installed and managed as a `systemd` service. The service file can be found at: +
`/usr/lib/systemd/system/influxdb.service`

The service should be running by default upon successfully provisioning the instance. The status can be checked via:
sudo systemctl status influxdb

This Quick Start uses an out-of-the-box setup for InfluxDB with very few changes. InfluxDB is used as a data storage layer for the AIT application.

=== AIT Server
The AIT-Core server is installed and managed as a `systemd` service. The service file can be found at: +
`/etc/systemd/system/ait-server.service`

The service should be running by default upon successfully provisioning the instance. The status can be checked via:

[source,bash]
sudo systemctl status ait-server

If changes are made to the AIT config files, the service will need to be restarted before changes are applied. This can be done via:

[source,bash]
sudo systemctl restart ait-server

The service itself will run the AIT Core Server which listens for, processes, and exposes telemetry. Additionally, any configured plugins (such as `AIT-GUI`) will also be run according to the main AIT config file.

== RHEL 8
All applications are deployed on Instances running the RHEL8 GA AMI. Although the applications installed do not have a hard dependency on this OS, it is the officially supported Operating System for all AMMOS applications.

== SELinux
SELinux is enabled and enforced on the application servers. Apache HTTP Server and the various application processes have been configured for SELinux compatibility and can be run without disabling SELinux.

Side effects may occur if settings and/or configuration files are modified or moved after the initial deployment of the application. If you have any issues with SELinux file and process contexts, please refer to a fresh deployment of the Quick Start or redeploy the Quick Start.

We highly recommend that you do not disable SELinux unless you are aware of unintended security consequences or have the need to disable SELinux for compatibility or debugging purposes.
